// @ts-expect-error Generated by the OpenNext Cloudflare build.
import handler from "./.open-next/worker.js";

interface WorkerEnv {
  MAINTENANCE_MODE?: string;
}

interface WorkerExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

const bypassHosts = new Set(["ascooo-new.garytsai07230723.workers.dev"]);
const maintenanceAssets = ["/_next/", "/assets/", "/favicon.ico"];

function legacyRedirect(url: URL) {
  let pathname = url.pathname;
  if (pathname === "/index.html") pathname = "/";
  else if (pathname === "/en/index.html") pathname = "/en";
  else pathname = pathname.replace(/\.html$/, "");
  pathname = pathname.replace(/^\/en\/(works|news)\//, "/$1/");
  if (pathname === url.pathname) return null;
  const target = new URL(url);
  target.pathname = pathname;
  return Response.redirect(target, 301);
}

const worker = {
  async fetch(request: Request, env: WorkerEnv, context: WorkerExecutionContext) {
    const url = new URL(request.url);
    const redirect = legacyRedirect(url);
    if (redirect) return redirect;

    const isMaintenance = String(env.MAINTENANCE_MODE).toLowerCase() === "true" && !bypassHosts.has(url.hostname);
    if (isMaintenance && !maintenanceAssets.some((prefix) => url.pathname.startsWith(prefix))) {
      if (url.pathname !== "/maintenance") return Response.redirect(new URL("/maintenance", url), 302);
      const response = await handler.fetch(request, env, context);
      return new Response(request.method === "HEAD" ? null : response.body, { status: 503, headers: { ...Object.fromEntries(response.headers), "Cache-Control": "no-store", "Retry-After": "3600", "X-Robots-Tag": "noindex, nofollow" } });
    }
    return handler.fetch(request, env, context);
  },
};

export default worker;
